### ISSUE TITLE
Integration of co-build for Spore to maximize the experience of using JoyID

### ISSUE THREAD

**Issue by ashuralyk** [sporeprotocol/spore-scrum#7]
# Description
currently, users have no method to peek the real data of signing message using JoyID in Spore website, to solve this and improve  the UX of Spore, we are building `co-build` feature which offers the `Typed Message` feature in CKB

now, ckb-vm team is pushing `co-build` feature to complete, after then, a simple method like `parse_message()` is provided for `spore-contract` to integrate

we should keep watching its progress in DC channel `papp-architecture` https://discord.com/channels/674518700518408213/1169476459044286494

# Related docs
https://www.notion.so/cryptape/Rev-4-CKB-Transaction-Co-Build-Protocol-TCoB-4740a2dd88e64e72ab1052f8e9acab1a

**Comment by ShookLyngs** [comment]
Spore-sdk is working on the feature, here's an overview issue to track updates of the sdk: 
- https://github.com/sporeprotocol/spore-sdk/issues/53

**Comment by ashuralyk** [comment]
co-build integration into contracts refers to here https://github.com/sporeprotocol/spore-contract/pull/28

**Comment by ashuralyk** [comment]
devnet repo has moved to spore org: https://github.com/sporeprotocol/spore-devenv

**Comment by ashuralyk** [comment]
integration done in PR https://github.com/sporeprotocol/spore-contract/pull/28
